export const allowedDomains: string[] = ['naver.com', 'daum.net'] as const;

export const subjects: { value: string; label: string }[] = [
  { value: 'Korean', label: '국어' },
  { value: 'English', label: '영어' },
  { value: 'Math', label: '수학' },
  { value: 'Ethics', label: '도덕' },
  { value: 'SocialStudies', label: '사회' },
  { value: 'History', label: '역사' },
  { value: 'KoreanHistory', label: '한국사' },
  { value: 'Science', label: '과학' },
  { value: 'TechnologyHome', label: '기술 가정' },
  { value: 'PhysicalEducation', label: '체육' },
  { value: 'Music', label: '음악' },
  { value: 'Art', label: '미술' },
  { value: 'ChineseCharacters', label: '한문' },
  { value: 'Chinese', label: '중국어' },
  { value: 'Japanese', label: '일본어' },
  { value: 'AccountingManagement', label: '회계/경영' },
  { value: 'Computer', label: '컴퓨터' },
  { value: 'CivilEngineering', label: '토목' },
  { value: 'Architecture', label: '건축' },
  { value: 'Mechanical', label: '기계' },
  { value: 'ElectricalElectronic', label: '전기 전자' },
  { value: 'Health', label: '보건' },
  { value: 'Cooking', label: '조리' },
  { value: 'Tourism', label: '관광' },
  { value: 'Baking', label: '제과' },
  { value: 'SecondForeignLanguage', label: '제 2외국어 과목' },
] as const;
