import Header from '@/components/header/header';
import { SidebarProvider, SidebarTrigger } from '@/components/sidebar/base-sidebar';
import MainSidebar from '@/components/sidebar/main-sidebar';
import { MSWProvider } from '@/lib/msw-provider';
import QueryProvider from '@/lib/tanstack-query-provider';

import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>
          <QueryProvider>
            <Header />
            <SidebarProvider className="fixed top-16 h-[calc(100vh-64px)]">
              <MainSidebar />
              <SidebarTrigger className="fixed left-2 top-[72px]" />
            </SidebarProvider>
            <main className="w-[calc(100vh - 16rem)] ml-64 mt-16 h-[calc(100vh-64px)] p-10">
              {children}
            </main>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
