import Header from '@/components/header/header';
import { MSWComponent } from '@/components/MSWComponent';

import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MSWComponent>{children}</MSWComponent>
        <Header />
      </body>
    </html>
  );
}
