import Header from '@/components/header/header';
import { SidebarProvider, SidebarTrigger } from '@/components/sidebar/base-sidebar';
import MainSidebar from '@/components/sidebar/main-sidebar';
import { MSWProvider } from '@/lib/msw-provider';
import QueryProvider from '@/lib/tanstack-query-provider';

import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <MSWProvider>
          <QueryProvider>
            <Header />
            <SidebarProvider>
              <MainSidebar />
              <SidebarTrigger className="fixed left-2 top-[72px]" />
              <main className="h-[calc(100vh-64px)] w-full overflow-y-auto p-10">{children}</main>
            </SidebarProvider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
